package com.hungteen.pvz.data;

import com.hungteen.pvz.PVZMod;
import com.hungteen.pvz.api.types.IPlantType;
import com.hungteen.pvz.common.block.BlockRegister;
import com.hungteen.pvz.common.item.ItemRegister;
import com.hungteen.pvz.common.item.misc.PVZSpawnEggItem;
import com.hungteen.pvz.common.item.spawn.card.PlantCardItem;
import com.hungteen.pvz.utils.StringUtil;
import net.minecraft.data.DataGenerator;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.client.model.generators.ItemModelBuilder;
import net.minecraftforge.client.model.generators.ItemModelProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class ItemModelGenerator extends ItemModelProvider {

	private final Set<Item> addedItems = new HashSet<>();

	public ItemModelGenerator(DataGenerator generator, ExistingFileHelper helper) {
		super(generator, PVZMod.MOD_ID, helper);
	}

	private ResourceLocation key(Item item) {
		return ForgeRegistries.ITEMS.getKey(item);
	}

	private ResourceLocation key(Block block) {
		return ForgeRegistries.BLOCKS.getKey(block);
	}

	@Override
	protected void registerModels() {
		// special model generated by blockbench.
		addedItems.addAll(Arrays.asList(ItemRegister.PEA_GUN.get(), ItemRegister.ZOMBIE_FLAG.get(), ItemRegister.BOBSLE_CAR.get(),
				ItemRegister.SCREEN_DOOR.get(), ItemRegister.JACK_BOX.get(), ItemRegister.BALLOON.get(),
				ItemRegister.WARNING_SIGN.get(), ItemRegister.ZOMBIE_DOLL.get(), ItemRegister.POLE.get(),
				ItemRegister.BUCKET_HEAD.get(), ItemRegister.RESOURCE_COLLECTOR.get(), ItemRegister.GARDEN_COMPASS.get()
		));

		// single add
		Arrays.asList(ItemRegister.PEA.get(), ItemRegister.SPORE.get(), ItemRegister.CABBAGE_SEEDS.get(), ItemRegister.CORN_SEEDS.get()
		).forEach(i -> {
			genNormalModel(i);
			this.addedItems.add(i);
		});

		Arrays.asList(BlockRegister.NUT_SAPLING.get(), BlockRegister.STEEL_LADDER.get()).forEach(i -> {
			genItemModelWithBlock(i.asItem());
			this.addedItems.add(i.asItem());
		});

		// for mostly common items.
		for (Item i : ForgeRegistries.ITEMS) {
			ResourceLocation itemKey = key(i);
			if (itemKey == null || !itemKey.getNamespace().equals(PVZMod.MOD_ID) || addedItems.contains(i)) continue;

			if (i instanceof PVZSpawnEggItem) { // for spawn eggs
				addedItems.add(i);
				getBuilder(itemKey.getPath()).parent(getExistingFile(ResourceLocation.fromNamespaceAndPath("minecraft", "item/template_spawn_egg")));
			} else if (i instanceof PlantCardItem) { // for plant cards
				IPlantType plant = ((PlantCardItem) i).plantType;
				ResourceLocation plantResource = ResourceLocation.fromNamespaceAndPath(plant.getModID(), "screenshot/plant/" + plant);
				addedItems.add(i);
				if (((PlantCardItem) i).isEnjoyCard) {
					ResourceLocation r = StringUtil.prefix("item/misc/mega_card");
					genNormal(itemKey.getPath(), r, plantResource);
				} else {
					genNormal(itemKey.getPath(), StringUtil.prefix("item/misc/" + plant.getRank().getName() + "_card"), plantResource);
				}
			} else if (i instanceof BlockItem) {
				addedItems.add(i);
				genBlockModel(((BlockItem) i).getBlock());
			}
		}

		// for hand held item
		Arrays.asList(ItemRegister.ORIGIN_AXE.get(), ItemRegister.ORIGIN_HOE.get(), ItemRegister.ORIGIN_PICKAXE.get(), ItemRegister.ORIGIN_SHOVEL.get(),
				ItemRegister.ORIGIN_SWORD.get()
		).forEach(i -> {
			addedItems.add(i);
			genHeld(key(i).getPath(), StringUtil.prefix("item/" + key(i).getPath()));
		});

		// 3 types of sun storage sapling.
		genSameModelsWithAdd(ItemRegister.SUN_STORAGE_SAPLING.get(), ItemRegister.SMALL_SUN_STORAGE_SAPLING.get(), ItemRegister.LARGE_SUN_STORAGE_SAPLING.get(), ItemRegister.ONCE_SUN_STORAGE_SAPLING.get());

		// last step for all normal item models.
		for (Item i : ForgeRegistries.ITEMS) {
			ResourceLocation itemKey = key(i);
			if (itemKey != null && itemKey.getNamespace().equals(PVZMod.MOD_ID) && !addedItems.contains(i)) {
				genNormal(itemKey.getPath(), StringUtil.prefix("item/" + itemKey.getPath()));
			}
		}
	}

	private void genSameModelsWithAdd(Item... items) {
		final Item first = items[0];
		for (Item i : items) {
			genNormal(key(i).getPath(), StringUtil.prefix("item/" + key(first).getPath()));
			this.addedItems.add(i);
		}
	}

	private void genNormalModel(Item i) {
		genNormal(key(i).getPath(), StringUtil.prefix("item/" + key(i).getPath()));
	}

	private ItemModelBuilder genNormal(String name, ResourceLocation... layers) {
		return gen(name, "item/generated", layers);
	}

	private ItemModelBuilder genHeld(String name, ResourceLocation... layers) {
		return gen(name, "item/handheld", layers);
	}

	private ItemModelBuilder gen(String name, String parent, ResourceLocation... layers) {
		ItemModelBuilder builder = withExistingParent(name, parent);
		for (int i = 0; i < layers.length; i++) {
			builder = builder.texture("layer" + i, layers[i]);
		}
		return builder;
	}

	private void genBlockModel(Block b) {
		withExistingParent(key(b).getPath(), StringUtil.prefix("block/" + key(b).getPath()));
	}

	private void genItemModelWithBlock(Item i) {
		genNormal(key(i).getPath(), StringUtil.prefix("block/" + key(i).getPath()));
	}

	@Override
	public String getName() {
		return "Plants vs Zombies item and itemblock models";
	}
}